### PR TITLE
Update SimpleContact.php

### PR DESCRIPTION
**Pull request by ribsousa**
Add dependency to RainLab Translate plugin, allow google captcha internationalization

### CODE REVIEW

**Review by jawainc — COMMENTED** [review]
this update conflicting with installation, I tried adding translate plugin dependency. But something with CMS its not auto installing RainLab.Translate plugin.

**Comment by ribsousa** [comment]
You add dependencecy?

```
<?php namespace Zainab\SimpleContact;
use System\Classes\PluginBase;
use Backend;
use RainLab\Translate\Models\Locale as LocaleModel;
use RainLab\Translate\Classes\Translator;
use Zainab\SimpleContact\Controllers\SimpleContact;
class Plugin extends PluginBase
{
```

**Comment by jawainc** [comment]
no i remove it

**Comment by ribsousa** [comment]
To auto install rainlab translate plugin you need to add these lines also in the file **Plugin.php**

```
use RainLab\Translate\Models\Locale as LocaleModel;
use RainLab\Translate\Classes\Translator;
```

**Comment by ribsousa** [comment]
To auto install rainlab translate plugin you need to add these lines also in the file **Plugin.php**
```
<?php namespace Zainab\SimpleContact;
   use System\Classes\PluginBase;
   use Backend;
   use RainLab\Translate\Models\Locale as LocaleModel;
   use RainLab\Translate\Classes\Translator;
   use Zainab\SimpleContact\Controllers\SimpleContact;
class Plugin extends PluginBase
{

/**
     * @var array   Require the RainLab.Translate plugin
     */
    public $require = ['RainLab.Translate'];
[...]
```

**Pull request merged**
